// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtRXwWhujLPld3b1gjYesOeNS325VGLyw',
    appId: '1:54275201983:web:23f1cd503d61f9c7171f0a',
    messagingSenderId: '54275201983',
    projectId: 'socialmediaapp-1e4e1',
    authDomain: 'socialmediaapp-1e4e1.firebaseapp.com',
    storageBucket: 'socialmediaapp-1e4e1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOmMSlHXoUCFdl7wwNCUKrhymYG8D4vAU',
    appId: '1:54275201983:android:c10760cf1df4ad70171f0a',
    messagingSenderId: '54275201983',
    projectId: 'socialmediaapp-1e4e1',
    storageBucket: 'socialmediaapp-1e4e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJhajMB9yCoLs0lVS6mXuxkm0xMX9fqHo',
    appId: '1:54275201983:ios:0753cf5af821b989171f0a',
    messagingSenderId: '54275201983',
    projectId: 'socialmediaapp-1e4e1',
    storageBucket: 'socialmediaapp-1e4e1.appspot.com',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJhajMB9yCoLs0lVS6mXuxkm0xMX9fqHo',
    appId: '1:54275201983:ios:0753cf5af821b989171f0a',
    messagingSenderId: '54275201983',
    projectId: 'socialmediaapp-1e4e1',
    storageBucket: 'socialmediaapp-1e4e1.appspot.com',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtRXwWhujLPld3b1gjYesOeNS325VGLyw',
    appId: '1:54275201983:web:617248515c24044c171f0a',
    messagingSenderId: '54275201983',
    projectId: 'socialmediaapp-1e4e1',
    authDomain: 'socialmediaapp-1e4e1.firebaseapp.com',
    storageBucket: 'socialmediaapp-1e4e1.appspot.com',
  );
}
