// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx2zREw0LRF_W8ia_LdLY0fA-ZZpVLYAM',
    appId: '1:148419100444:web:5b49d39db62004fdffc4d9',
    messagingSenderId: '148419100444',
    projectId: 'authpractice-f8032',
    authDomain: 'authpractice-f8032.firebaseapp.com',
    storageBucket: 'authpractice-f8032.appspot.com',
    measurementId: 'G-FF0MBCEHQY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpuopIA_fSfyaO7Q2vg0H56yPnLFcDs5c',
    appId: '1:148419100444:android:24d148c97c435899ffc4d9',
    messagingSenderId: '148419100444',
    projectId: 'authpractice-f8032',
    storageBucket: 'authpractice-f8032.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARzdp5UAdJWcP8m0OOhdtBpcRiA5uqmg0',
    appId: '1:148419100444:ios:c769117462b9a004ffc4d9',
    messagingSenderId: '148419100444',
    projectId: 'authpractice-f8032',
    storageBucket: 'authpractice-f8032.appspot.com',
    iosBundleId: 'com.example.authPractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARzdp5UAdJWcP8m0OOhdtBpcRiA5uqmg0',
    appId: '1:148419100444:ios:c769117462b9a004ffc4d9',
    messagingSenderId: '148419100444',
    projectId: 'authpractice-f8032',
    storageBucket: 'authpractice-f8032.appspot.com',
    iosBundleId: 'com.example.authPractice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDx2zREw0LRF_W8ia_LdLY0fA-ZZpVLYAM',
    appId: '1:148419100444:web:9680ca3014ce1c55ffc4d9',
    messagingSenderId: '148419100444',
    projectId: 'authpractice-f8032',
    authDomain: 'authpractice-f8032.firebaseapp.com',
    storageBucket: 'authpractice-f8032.appspot.com',
    measurementId: 'G-7SLK97JV6P',
  );
}
